from typing import List, Dict

from gpt4all import GPT4All


class Bot:
    def __init__(self, max_tokens=0) -> None:
        self.max_tokens = max_tokens
        self.model = GPT4All('gpt4all-13b-snoozy-q4_0.gguf')

    def generate(self, prompt: str) -> str:
        """
        Given a prompt, generate the response from the bot.
        :param prompt: Input to the model, string
        :return: A string of the response generated by the bot
        """
        # TODO: if the model cannot provide a specific answer redirect
        return self.model.generate(prompt, max_tokens=self.max_tokens)

    def start_chat_session(self) -> None:
        chat = True
        with self.model.chat_session():
            # TODO initialize chat session
            while chat:
                new_input = input('Type something > ')
                if new_input == 'END':
                    chat = False
                    print(self.get_chat_session())  # TODO store chat session
                else:
                    print(self.generate(new_input))

    def get_chat_session(self) -> List[Dict[str, str]]:
        """
        Return the current chat session of the bot
        :return: List of Dicts
        """
        return self.model.current_chat_session
